/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_opencv_demo_HelloJni */

#ifndef _Included_com_opencv_demo_HelloJni
#define _Included_com_opencv_demo_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_opencv_demo_HelloJni
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_opencv_1demo_HelloJni_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
